apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb-jmeter
  labels:
    app: influxdb-jmeter
spec:
  replicas: 1
  serviceName: influxdb-jmeter
  selector:
    matchLabels:
      app: influxdb-jmeter
  template:
    metadata:
      labels:
        app: influxdb-jmeter
    spec:
      containers:
        - image: influxdb
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
          - name: config-volume
            mountPath: /etc/influxdb
          - name: influxdbdir
            mountPath: /var/lib/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
      volumes:
      - name: config-volume
        configMap:
         name: influxdb-config
  volumeClaimTemplates:
  - metadata:
      name: influxdbdir
    spec:
      storageClassName: encrypted-gp2
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
